@url=http://localhost:59829


### Get inventories
GET {{url}}/api/inventories?pageIndex=1&pageSize=10 HTTP/1.1


### Get Products
GET {{url}}/api/products?pageIndex=1&pageSize=100 HTTP/1.1


### Create Inventory
POST {{url}}/api/inventory HTTP/1.1
Content-Type: application/json

{
    "name": "Test",
    "location": "HELELELELE"
}
