// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleStore.Inventory.Infrastructure.EfCore.Persistence;

namespace SimpleStore.Inventory.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20200311102222_Add_Inventory")]
    partial class Add_Inventory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleStore.Inventory.Domain.Models.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            InventoryId = new Guid("0ecf66a2-7fc0-48ba-8d24-5a567c7ea8ee"),
                            Location = "Inventory-1-Location",
                            Name = "Inventory-1"
                        },
                        new
                        {
                            InventoryId = new Guid("1e4330ff-fe3a-4fbb-8878-8cecf04dd31f"),
                            Location = "Inventory-2-Location",
                            Name = "Inventory-2"
                        },
                        new
                        {
                            InventoryId = new Guid("ad6a188d-db6d-4f47-a103-e3d12ee6cc36"),
                            Location = "Inventory-3-Location",
                            Name = "Inventory-3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
