// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleStore.ProductCatalog.Infrastructure.EfCore.Persistence;

namespace SimpleStore.ProductCatalog.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(ProductCatalogDbContext))]
    partial class ProductCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleStore.ProductCatalog.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("4a2abe51-e895-49be-878a-0729535ba92e"),
                            Code = "PRD-1",
                            Name = "Product-1"
                        },
                        new
                        {
                            ProductId = new Guid("1d250f1d-1546-47f3-92d2-31fbf87a3511"),
                            Code = "PRD-2",
                            Name = "Product-2"
                        },
                        new
                        {
                            ProductId = new Guid("4012d62c-2bea-42eb-9e64-d7b22185c4f0"),
                            Code = "PRD-3",
                            Name = "Product-3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
